using System;
using System.Collections.Specialized;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using GeneralToolkitLib.Converters;

namespace GeneralToolkitLib.Hashing
{
    public class ChecksumFileGenerator
    {
        private const string CHECKSUM_FILE_HEADER = "; Generated by {0} on {1} at {2} \n; http://www.cuplex.se\n;";
        private const string CHECKSUM_FILE_INFO = ";{0}  {1} {2} {3}";
        private readonly string _applicationName;
        private readonly IProgress<ChecksumProgress> _progress;
        private readonly ChecksumProgress checksumProgress;

        public ChecksumFileGenerator(string applicationName, IProgress<ChecksumProgress> progress)
        {
            _applicationName = applicationName;
            _progress = progress;
            checksumProgress = new ChecksumProgress();
        }

        public void GenrateSFVFileAsync(StringCollection filePathCollection, string sfvFilename)
        {
            new Task(() => GenrateSFVFile(filePathCollection, sfvFilename)).Start();
        }

        public void GenrateSFVFile(StringCollection filePathCollection, string sfvFilename)
        {
            using (FileStream fs = File.Create(sfvFilename))
            {
                CRC32 CRC32HashImplemenation = new CRC32();

                // Write Header
                StreamWriter sw = new StreamWriter(fs);
                sw.WriteLine(CHECKSUM_FILE_HEADER, _applicationName, DateTime.Now.ToString("yyyy-MM-dd"), DateTime.Now.ToString("HH:mm:ss"));

                checksumProgress.FilesTotal = filePathCollection.Count;
                checksumProgress.Text = "Generating SFV file header";

                if (_progress != null)
                    _progress.Report(checksumProgress);

                foreach (string filename in filePathCollection)
                {
                    FileInfo fileInfo = new FileInfo(filename);

                    if (!fileInfo.Exists)
                    {
                        checksumProgress.FilesTotal = checksumProgress.FilesTotal - 1;
                        continue;
                    }

                    sw.WriteLine(CHECKSUM_FILE_INFO, FormatFileSize(fileInfo.Length, 14), fileInfo.LastWriteTime.ToString("HH:mm:ss"), fileInfo.LastWriteTime.ToString("yyyy-MM-dd"), GeneralConverters.GetFileNameFromPath(filename));
                }

                foreach (string filename in filePathCollection)
                {
                    checksumProgress.Text = "Processing file: " + filename;

                    if (_progress != null)
                        _progress.Report(checksumProgress);

                    FileInfo fileInfo = new FileInfo(filename);

                    if (!fileInfo.Exists)
                        continue;
                    try
                    {
                        string hexChecksum = GeneralConverters.ByteArrayToHexString(CRC32HashImplemenation.ComputeHash(fileInfo.OpenRead()));
                        sw.WriteLine(GeneralConverters.GetFileNameFromPath(filename) + " " + hexChecksum);
                        checksumProgress.DataRead = checksumProgress.DataRead + fileInfo.Length;
                    }
                    catch (Exception ex)
                    {
                        checksumProgress.Text = ex.Message;
                    }


                    checksumProgress.FilesCompleted = checksumProgress.FilesCompleted + 1;
                    checksumProgress.TotalProgress = (checksumProgress.FilesCompleted * 100) / checksumProgress.FilesTotal;

                    if (_progress != null)
                        _progress.Report(checksumProgress);
                }

                fs.Flush();
                fs.Close();

                if (_progress != null)
                {
                    checksumProgress.Text = "SFV file generation completed";
                    checksumProgress.TotalProgress = 100;
                    checksumProgress.Completed = true;
                    _progress.Report(checksumProgress);
                }
            }
        }

        public void GenrateMD5FileAsync(StringCollection filePathCollection, string sfvFilename)
        {
            new Task(() => GenrateMD5File(filePathCollection, sfvFilename)).Start();
        }

        public void GenrateMD5File(StringCollection filePathCollection, string sfvFilename)
        {
            using (FileStream fs = File.Create(sfvFilename))
            {
                MD5 MD5HashImplemenation = new MD5();

                // Write Header
                StreamWriter sw = new StreamWriter(fs);
                sw.WriteLine(CHECKSUM_FILE_HEADER, _applicationName, DateTime.Now.ToString("yyyy-MM-dd"), DateTime.Now.ToString("HH:mm:ss"));

                checksumProgress.FilesTotal = filePathCollection.Count;
                checksumProgress.Text = "Generating MD5 file header";

                if (_progress != null)
                    _progress.Report(checksumProgress);

                foreach (string filename in filePathCollection)
                {
                    FileInfo fileInfo = new FileInfo(filename);

                    if (!fileInfo.Exists)
                    {
                        checksumProgress.FilesTotal = checksumProgress.FilesTotal - 1;
                        continue;
                    }

                    sw.WriteLine(CHECKSUM_FILE_INFO, FormatFileSize(fileInfo.Length, 14), fileInfo.LastWriteTime.ToString("HH:mm:ss"), fileInfo.LastWriteTime.ToString("yyyy-MM-dd"), GeneralConverters.GetFileNameFromPath(filename));
                }

                foreach (string filename in filePathCollection)
                {
                    checksumProgress.Text = "Processing file: " + filename;

                    if (_progress != null)
                        _progress.Report(checksumProgress);

                    FileInfo fileInfo = new FileInfo(filename);

                    if (!fileInfo.Exists)
                        continue;
                    try
                    {
                        string hexChecksum = GeneralConverters.ByteArrayToHexString(MD5HashImplemenation.ComputeHash(fileInfo.OpenRead()));
                        sw.WriteLine(hexChecksum + " *" + GeneralConverters.GetFileNameFromPath(filename));
                        checksumProgress.DataRead = checksumProgress.DataRead + fileInfo.Length;
                    }
                    catch (Exception ex)
                    {
                        checksumProgress.Text = ex.Message;
                    }


                    checksumProgress.FilesCompleted = checksumProgress.FilesCompleted + 1;
                    checksumProgress.TotalProgress = (checksumProgress.FilesCompleted * 100) / checksumProgress.FilesTotal;

                    if (_progress != null)
                        _progress.Report(checksumProgress);
                }

                sw.Flush();
                fs.Flush();
                fs.Close();

                if (_progress != null)
                {
                    checksumProgress.Text = "MD5 file generation completed";
                    checksumProgress.TotalProgress = 100;
                    checksumProgress.Completed = true;
                    _progress.Report(checksumProgress);
                }
            }
        }

        private string FormatFileSize(long fileSize, int strLen)
        {
            return fileSize.ToString(CultureInfo.InvariantCulture).PadLeft(strLen);
        }
    }
}