//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeleteDuplicateFiles.TerminologyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchStringComparison", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Terminology.WebService.Index.Co" +
        "re")]
    public enum SearchStringComparison : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaseInsensitive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaseSensitive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HotKeyAndCaseSensitive = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchOperator", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Terminology.WebService.Index.Co" +
        "re")]
    public enum SearchOperator : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exact = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contains = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnyWord = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TranslationSources", Namespace="http://api.terminology.microsoft.com/terminology", ItemName="TranslationSource")]
    [System.SerializableAttribute()]
    public class TranslationSources : System.Collections.Generic.List<DeleteDuplicateFiles.TerminologyService.TranslationSource> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationSource", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Terminology.WebService.Index.En" +
        "tities")]
    public enum TranslationSource : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Terms = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UiStrings = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Products", Namespace="http://api.terminology.microsoft.com/terminology", ItemName="Product")]
    [System.SerializableAttribute()]
    public class Products : System.Collections.Generic.List<DeleteDuplicateFiles.TerminologyService.Product> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class Product : DeleteDuplicateFiles.TerminologyService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeleteDuplicateFiles.TerminologyService.Versions VersionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeleteDuplicateFiles.TerminologyService.Versions Versions {
            get {
                return this.VersionsField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionsField, value) != true)) {
                    this.VersionsField = value;
                    this.RaisePropertyChanged("Versions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeleteDuplicateFiles.TerminologyService.Version))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeleteDuplicateFiles.TerminologyService.Language))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeleteDuplicateFiles.TerminologyService.Product))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Version", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class Version : DeleteDuplicateFiles.TerminologyService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class Language : DeleteDuplicateFiles.TerminologyService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Versions", Namespace="http://api.terminology.microsoft.com/terminology", ItemName="Version")]
    [System.SerializableAttribute()]
    public class Versions : System.Collections.Generic.List<DeleteDuplicateFiles.TerminologyService.Version> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Matches", Namespace="http://api.terminology.microsoft.com/terminology", ItemName="Match")]
    [System.SerializableAttribute()]
    public class Matches : System.Collections.Generic.List<DeleteDuplicateFiles.TerminologyService.Match> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConfidenceLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefinitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<DeleteDuplicateFiles.TerminologyService.TranslationSource> SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeleteDuplicateFiles.TerminologyService.Translations TranslationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfidenceLevel {
            get {
                return this.ConfidenceLevelField;
            }
            set {
                if ((this.ConfidenceLevelField.Equals(value) != true)) {
                    this.ConfidenceLevelField = value;
                    this.RaisePropertyChanged("ConfidenceLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Definition {
            get {
                return this.DefinitionField;
            }
            set {
                if ((object.ReferenceEquals(this.DefinitionField, value) != true)) {
                    this.DefinitionField = value;
                    this.RaisePropertyChanged("Definition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalText {
            get {
                return this.OriginalTextField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalTextField, value) != true)) {
                    this.OriginalTextField = value;
                    this.RaisePropertyChanged("OriginalText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductVersion {
            get {
                return this.ProductVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductVersionField, value) != true)) {
                    this.ProductVersionField = value;
                    this.RaisePropertyChanged("ProductVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<DeleteDuplicateFiles.TerminologyService.TranslationSource> Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeleteDuplicateFiles.TerminologyService.Translations Translations {
            get {
                return this.TranslationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationsField, value) != true)) {
                    this.TranslationsField = value;
                    this.RaisePropertyChanged("Translations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Translations", Namespace="http://api.terminology.microsoft.com/terminology", ItemName="Translation")]
    [System.SerializableAttribute()]
    public class Translations : System.Collections.Generic.List<DeleteDuplicateFiles.TerminologyService.Translation> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Translation", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class Translation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslatedTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslatedText {
            get {
                return this.TranslatedTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslatedTextField, value) != true)) {
                    this.TranslatedTextField = value;
                    this.RaisePropertyChanged("TranslatedText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFault", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeleteDuplicateFiles.TerminologyService.MissingParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeleteDuplicateFiles.TerminologyService.InvalidParameters))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeleteDuplicateFiles.TerminologyService.Unexpected))]
    public partial class BaseFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissingParameter", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class MissingParameter : DeleteDuplicateFiles.TerminologyService.BaseFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterName {
            get {
                return this.ParameterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterNameField, value) != true)) {
                    this.ParameterNameField = value;
                    this.RaisePropertyChanged("ParameterName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidParameters", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class InvalidParameters : DeleteDuplicateFiles.TerminologyService.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unexpected", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class Unexpected : DeleteDuplicateFiles.TerminologyService.BaseFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Languages", Namespace="http://api.terminology.microsoft.com/terminology", ItemName="Language")]
    [System.SerializableAttribute()]
    public class Languages : System.Collections.Generic.List<DeleteDuplicateFiles.TerminologyService.Language> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Capability", Namespace="http://api.terminology.microsoft.com/terminology")]
    [System.SerializableAttribute()]
    public partial class Capability : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SupportsAnyToAnyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SupportsAnyToEnUsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SupportsEnUsToAnyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsAnyToAny {
            get {
                return this.SupportsAnyToAnyField;
            }
            set {
                if ((this.SupportsAnyToAnyField.Equals(value) != true)) {
                    this.SupportsAnyToAnyField = value;
                    this.RaisePropertyChanged("SupportsAnyToAny");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsAnyToEnUs {
            get {
                return this.SupportsAnyToEnUsField;
            }
            set {
                if ((this.SupportsAnyToEnUsField.Equals(value) != true)) {
                    this.SupportsAnyToEnUsField = value;
                    this.RaisePropertyChanged("SupportsAnyToEnUs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsEnUsToAny {
            get {
                return this.SupportsEnUsToAnyField;
            }
            set {
                if ((this.SupportsEnUsToAnyField.Equals(value) != true)) {
                    this.SupportsEnUsToAnyField = value;
                    this.RaisePropertyChanged("SupportsEnUsToAny");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.terminology.microsoft.com/terminology", ConfigurationName="TerminologyService.Terminology")]
    public interface Terminology {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslations", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeleteDuplicateFiles.TerminologyService.Unexpected), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsUnexp" +
            "ectedFault", Name="Unexpected")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeleteDuplicateFiles.TerminologyService.MissingParameter), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsMissi" +
            "ngParameterFault", Name="MissingParameter")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeleteDuplicateFiles.TerminologyService.InvalidParameters), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsInval" +
            "idParametersFault", Name="InvalidParameters")]
        DeleteDuplicateFiles.TerminologyService.Matches GetTranslations(string text, string from, string to, DeleteDuplicateFiles.TerminologyService.SearchStringComparison sensitivity, DeleteDuplicateFiles.TerminologyService.SearchOperator searchOperator, DeleteDuplicateFiles.TerminologyService.TranslationSources sources, System.Nullable<bool> unique, int maxTranslations, bool includeDefinitions, DeleteDuplicateFiles.TerminologyService.Products products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslations", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsRespo" +
            "nse")]
        System.Threading.Tasks.Task<DeleteDuplicateFiles.TerminologyService.Matches> GetTranslationsAsync(string text, string from, string to, DeleteDuplicateFiles.TerminologyService.SearchStringComparison sensitivity, DeleteDuplicateFiles.TerminologyService.SearchOperator searchOperator, DeleteDuplicateFiles.TerminologyService.TranslationSources sources, System.Nullable<bool> unique, int maxTranslations, bool includeDefinitions, DeleteDuplicateFiles.TerminologyService.Products products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetLanguages", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetLanguagesResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeleteDuplicateFiles.TerminologyService.Unexpected), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetLanguagesUnexpect" +
            "edFault", Name="Unexpected")]
        DeleteDuplicateFiles.TerminologyService.Languages GetLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetLanguages", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetLanguagesResponse" +
            "")]
        System.Threading.Tasks.Task<DeleteDuplicateFiles.TerminologyService.Languages> GetLanguagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetProducts", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeleteDuplicateFiles.TerminologyService.Unexpected), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetProductsUnexpecte" +
            "dFault", Name="Unexpected")]
        DeleteDuplicateFiles.TerminologyService.Products GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetProducts", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetProductsResponse")]
        System.Threading.Tasks.Task<DeleteDuplicateFiles.TerminologyService.Products> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetCapability", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetCapabilityRespons" +
            "e")]
        DeleteDuplicateFiles.TerminologyService.Capability GetCapability();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetCapability", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetCapabilityRespons" +
            "e")]
        System.Threading.Tasks.Task<DeleteDuplicateFiles.TerminologyService.Capability> GetCapabilityAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TerminologyChannel : DeleteDuplicateFiles.TerminologyService.Terminology, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminologyClient : System.ServiceModel.ClientBase<DeleteDuplicateFiles.TerminologyService.Terminology>, DeleteDuplicateFiles.TerminologyService.Terminology {
        
        public TerminologyClient() {
        }
        
        public TerminologyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminologyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminologyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminologyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DeleteDuplicateFiles.TerminologyService.Matches GetTranslations(string text, string from, string to, DeleteDuplicateFiles.TerminologyService.SearchStringComparison sensitivity, DeleteDuplicateFiles.TerminologyService.SearchOperator searchOperator, DeleteDuplicateFiles.TerminologyService.TranslationSources sources, System.Nullable<bool> unique, int maxTranslations, bool includeDefinitions, DeleteDuplicateFiles.TerminologyService.Products products) {
            return base.Channel.GetTranslations(text, from, to, sensitivity, searchOperator, sources, unique, maxTranslations, includeDefinitions, products);
        }
        
        public System.Threading.Tasks.Task<DeleteDuplicateFiles.TerminologyService.Matches> GetTranslationsAsync(string text, string from, string to, DeleteDuplicateFiles.TerminologyService.SearchStringComparison sensitivity, DeleteDuplicateFiles.TerminologyService.SearchOperator searchOperator, DeleteDuplicateFiles.TerminologyService.TranslationSources sources, System.Nullable<bool> unique, int maxTranslations, bool includeDefinitions, DeleteDuplicateFiles.TerminologyService.Products products) {
            return base.Channel.GetTranslationsAsync(text, from, to, sensitivity, searchOperator, sources, unique, maxTranslations, includeDefinitions, products);
        }
        
        public DeleteDuplicateFiles.TerminologyService.Languages GetLanguages() {
            return base.Channel.GetLanguages();
        }
        
        public System.Threading.Tasks.Task<DeleteDuplicateFiles.TerminologyService.Languages> GetLanguagesAsync() {
            return base.Channel.GetLanguagesAsync();
        }
        
        public DeleteDuplicateFiles.TerminologyService.Products GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<DeleteDuplicateFiles.TerminologyService.Products> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public DeleteDuplicateFiles.TerminologyService.Capability GetCapability() {
            return base.Channel.GetCapability();
        }
        
        public System.Threading.Tasks.Task<DeleteDuplicateFiles.TerminologyService.Capability> GetCapabilityAsync() {
            return base.Channel.GetCapabilityAsync();
        }
    }
}
