//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voc_ScriptGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voc_ScriptGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer link: Agent view.
        /// </summary>
        internal static string Agent_View {
            get {
                return ResourceManager.GetString("Agent_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using voc länk (Original &quot;category_20074573&quot;).
        /// </summary>
        internal static string category_20074573 {
            get {
                return ResourceManager.GetString("category_20074573", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ forum länk (original &quot;category_20085466&quot;).
        /// </summary>
        internal static string category_20085466 {
            get {
                return ResourceManager.GetString("category_20085466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer link: Contact Us.
        /// </summary>
        internal static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Forums.
        /// </summary>
        internal static string FAQ_Forums_LinkText {
            get {
                return ResourceManager.GetString("FAQ_Forums_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /categories/20085466-FAQ-Forums.
        /// </summary>
        internal static string FAQ_Forums_URL {
            get {
                return ResourceManager.GetString("FAQ_Forums_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to original Found this useful?.
        /// </summary>
        internal static string Found_this_useful {
            get {
                return ResourceManager.GetString("Found_this_useful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string Get_Started {
            get {
                return ResourceManager.GetString("Get_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /entries/23171528-Get-started-with-Volvo-On-Call.
        /// </summary>
        internal static string GetStartedWithVoc_LinkURL {
            get {
                return ResourceManager.GetString("GetStartedWithVoc_LinkURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host base url. For Example https://cuplex.se/voc.
        /// </summary>
        internal static string Hosting_Base_URL {
            get {
                return ResourceManager.GetString("Hosting_Base_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know!.
        /// </summary>
        internal static string Let_us_know {
            get {
                return ResourceManager.GetString("Let_us_know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer link: Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;b&gt;Information&lt;/b&gt;&lt;/h2&gt;&lt;p&gt;Fields marked with an asterisk (*) are mandatory. For faster help, be detailed in the description of your problem. &lt;/p&gt;&lt;p&gt;We operate Mon-Fri from 8.00-17.00 (CET) and will try to answer your question as quickly as possible. You will receive the answer to your question via email.&lt;/p&gt; &lt;p&gt;Please note that this form is only for questions related to Volvo On Call. For other problems with your Volvo, we refer to your local dealer. We will answer requests written in English.&lt;/p&gt;.
        /// </summary>
        internal static string NewRequest_Sidebox_HTML {
            get {
                return ResourceManager.GetString("NewRequest_Sidebox_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular topics:.
        /// </summary>
        internal static string Popular_topics {
            get {
                return ResourceManager.GetString("Popular_topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer link: Privacy &amp; Cookies.
        /// </summary>
        internal static string Privacy_Cookies {
            get {
                return ResourceManager.GetString("Privacy_Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search form: Search in this category.
        /// </summary>
        internal static string Search_this_category {
            get {
                return ResourceManager.GetString("Search_this_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer link: Sign out.
        /// </summary>
        internal static string Sign_out {
            get {
                return ResourceManager.GetString("Sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change New request header: Submit a request for assistance..
        /// </summary>
        internal static string Submit_a_request_for_assistance {
            get {
                return ResourceManager.GetString("Submit_a_request_for_assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svenska.
        /// </summary>
        internal static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer link: Terms of Use.
        /// </summary>
        internal static string Terms_of_Use {
            get {
                return ResourceManager.GetString("Terms_of_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Top_Header_Search {
            get {
                return ResourceManager.GetString("Top_Header_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guides.
        /// </summary>
        internal static string User_Guides {
            get {
                return ResourceManager.GetString("User_Guides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /forums/21614081-How-to.
        /// </summary>
        internal static string User_Guides_URL {
            get {
                return ResourceManager.GetString("User_Guides_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Volvo On Call?.
        /// </summary>
        internal static string WhatIsVoc_LinkText {
            get {
                return ResourceManager.GetString("WhatIsVoc_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /entries/22987852-What-is-Volvo-On-Call-.
        /// </summary>
        internal static string WhatIsVoc_URL {
            get {
                return ResourceManager.GetString("WhatIsVoc_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to original &quot;0 people found this useful.&quot;.
        /// </summary>
        internal static string zero_people_found_this_useful {
            get {
                return ResourceManager.GetString("zero_people_found_this_useful", resourceCulture);
            }
        }
    }
}
