//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureMemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureMemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApplicationUpdateLogo {
            get {
                object obj = ResourceManager.GetObject("ApplicationUpdateLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save.
        /// </summary>
        internal static string FormMain__Could_not_save {
            get {
                return ResourceManager.GetString("FormMain__Could_not_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Saved.
        /// </summary>
        internal static string FormMain__Database_Saved {
            get {
                return ResourceManager.GetString("FormMain__Database_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading application settings.
        /// </summary>
        internal static string FormMain__Error_loading_application_settings {
            get {
                return ResourceManager.GetString("FormMain__Error_loading_application_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string FormMain__ErrorText {
            get {
                return ResourceManager.GetString("FormMain__ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string FormMain__Not_found {
            get {
                return ResourceManager.GetString("FormMain__Not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search string not found.
        /// </summary>
        internal static string FormMain__Search_string_not_found {
            get {
                return ResourceManager.GetString("FormMain__Search_string_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed successfully.
        /// </summary>
        internal static string FormMain_Backup_completed_successfully {
            get {
                return ResourceManager.GetString("FormMain_Backup_completed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to backup database.
        /// </summary>
        internal static string FormMain_Failed_to_backup_database {
            get {
                return ResourceManager.GetString("FormMain_Failed_to_backup_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Folder is disabled in settings.
        /// </summary>
        internal static string FormMain_saveToSharedFolderMenuDisabled {
            get {
                return ResourceManager.GetString("FormMain_saveToSharedFolderMenuDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Folder path is not valid.
        /// </summary>
        internal static string FormMain_saveToSharedFoldrMenuInvalidPath {
            get {
                return ResourceManager.GetString("FormMain_saveToSharedFoldrMenuInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.cuplex.se/SecureMemo/versionInfo.txt.
        /// </summary>
        internal static string VersionInfoUrl {
            get {
                return ResourceManager.GetString("VersionInfoUrl", resourceCulture);
            }
        }
    }
}
